// mavis-form-submit
// Contact form backend for websites generated by MAVIS.
// Accepts POST from public client websites (no Supabase JWT).
// verify_jwt = false (see supabase/config.toml)
//
// Supported Content-Types:
//   application/json
//   application/x-www-form-urlencoded
//
// Required body fields:
//   user_id  — Supabase auth user UUID of the website owner
//   email OR phone — at least one contact field
//
// Optional body fields:
//   project_id, name, message, form_type (defaults to "contact")

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const SB_URL = Deno.env.get("SUPABASE_URL")!;
const SB_SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BOT_TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN") ?? "";
const GLOBAL_CHAT_ID = Deno.env.get("TELEGRAM_CHAT_ID") ?? "";

const adminSb = createClient(SB_URL, SB_SERVICE_KEY, { auth: { persistSession: false } });

// ── Telegram helper ───────────────────────────────────────────
async function sendTelegram(chatId: string, text: string): Promise<void> {
  if (!BOT_TOKEN || !chatId) return;
  const payload = text.length > 4096 ? text.slice(0, 4056) + "\n…[truncated]" : text;
  await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: chatId, text: payload, parse_mode: "Markdown" }),
  }).catch(() => {});
}

// ── Look up the website owner's Telegram chat ID ─────────────
async function getUserTelegramChatId(userId: string): Promise<string> {
  // First try mavis_tacit where key = 'telegram_chat_id' for this user
  const { data: tacit } = await adminSb
    .from("mavis_tacit")
    .select("value")
    .eq("user_id", userId)
    .eq("key", "telegram_chat_id")
    .maybeSingle();

  if (tacit?.value) return String(tacit.value);

  // Fall back to profiles.telegram_chat_id if the column exists
  const { data: profile } = await adminSb
    .from("profiles")
    .select("telegram_chat_id")
    .eq("id", userId)
    .maybeSingle();

  if ((profile as any)?.telegram_chat_id) return String((profile as any).telegram_chat_id);

  // Last resort: global env var
  return GLOBAL_CHAT_ID;
}

// ── Parse request body (JSON or form-encoded) ─────────────────
async function parseBody(req: Request): Promise<Record<string, string>> {
  const ct = req.headers.get("content-type") ?? "";

  if (ct.includes("application/x-www-form-urlencoded")) {
    const text = await req.text();
    const params = new URLSearchParams(text);
    const out: Record<string, string> = {};
    params.forEach((v, k) => { out[k] = v; });
    return out;
  }

  // Default to JSON
  return await req.json().catch(() => ({}));
}

// ── Edge Function entry point ─────────────────────────────────
serve(async (req) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const json = (data: unknown, status = 200) =>
    new Response(JSON.stringify(data), {
      status,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  if (req.method !== "POST") {
    return json({ success: false, error: "Method not allowed" }, 405);
  }

  try {
    const body = await parseBody(req);

    // ── Validation ──────────────────────────────────────────
    if (!body.user_id) {
      return json({ success: false, error: "user_id is required" }, 400);
    }
    if (!body.email && !body.phone) {
      return json({ success: false, error: "At least one of email or phone is required" }, 400);
    }

    // ── Store submission ────────────────────────────────────
    const { error: insertErr } = await adminSb.from("website_form_submissions").insert({
      project_id: body.project_id ?? null,
      user_id: body.user_id,
      form_type: body.form_type ?? "contact",
      data: {
        name: body.name,
        email: body.email,
        phone: body.phone,
        message: body.message,
      },
      notified: false,
    });

    if (insertErr) {
      console.error("[mavis-form-submit] insert error:", insertErr.message);
      return json({ success: false, error: "Failed to save submission" }, 500);
    }

    // ── Build Telegram notification ─────────────────────────
    const lines: string[] = ["📬 *New Lead from Your Website*", ""];

    if (body.name)    lines.push(`Name: ${body.name}`);
    if (body.email)   lines.push(`Email: ${body.email}`);
    if (body.phone)   lines.push(`Phone: ${body.phone}`);
    if (body.message) lines.push(`Message: ${body.message.slice(0, 300)}${body.message.length > 300 ? "…" : ""}`);

    // Resolve project name for context
    let websiteLabel = body.project_id ?? "unknown";
    if (body.project_id) {
      const { data: proj } = await adminSb
        .from("website_projects")
        .select("business_name, project_name")
        .eq("id", body.project_id)
        .maybeSingle();
      if (proj) websiteLabel = (proj as any).business_name || (proj as any).project_name || body.project_id;
    }
    lines.push("", `Website: ${websiteLabel}`);

    const chatId = await getUserTelegramChatId(body.user_id);
    if (chatId) {
      await sendTelegram(chatId, lines.join("\n"));

      // Mark as notified
      await adminSb
        .from("website_form_submissions")
        .update({ notified: true })
        .eq("user_id", body.user_id)
        .eq("notified", false)
        .order("created_at", { ascending: false })
        .limit(1);
    }

    return json({ success: true, message: "Message received! We'll be in touch soon." });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[mavis-form-submit]", msg);
    return json({ success: false, error: "Internal server error" }, 500);
  }
});
