// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}
function errorResult(msg) {
  return { content: [{ type: "text", text: msg }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in VANTARA user id and email for the connected client.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    return jsonResult({
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    });
  }
});

// src/lib/mcp/tools/list-councils.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_councils_default = defineTool2({
  name: "list_councils",
  title: "List council members",
  description: "List the signed-in user's Council members (AI advisors) with role, specialty, and personality.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("councils").select("id,name,role,specialty,class,personality_prompt,last_used_at,created_at").order("last_used_at", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-personas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_personas_default = defineTool3({
  name: "list_personas",
  title: "List personas",
  description: "List the signed-in user's Personas with archetype, role, and system prompt.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional(),
    active_only: z2.boolean().optional().describe("If true, only return active personas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, active_only }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("personas").select("id,name,archetype,role,system_prompt,is_active,model,created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (active_only) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-quests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_quests_default = defineTool4({
  name: "list_quests",
  title: "List quests",
  description: "List the signed-in user's active quests (tasks/goals) with status, difficulty, and deadline.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional(),
    category: z3.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("quests").select("id,description,category,difficulty,deadline,phase,current_state,progress_current,codex_points_reward,created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/create-quest.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_quest_default = defineTool5({
  name: "create_quest",
  title: "Create quest",
  description: "Create a new quest (task/goal) for the signed-in user.",
  inputSchema: {
    description: z4.string().min(1).describe("What the quest is."),
    category: z4.string().optional(),
    difficulty: z4.enum(["easy", "medium", "hard", "epic", "legendary"]).optional(),
    deadline: z4.string().optional().describe("ISO 8601 datetime."),
    codex_points_reward: z4.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("quests").insert({
      user_id: ctx.getUserId(),
      description: input.description,
      category: input.category ?? null,
      difficulty: input.difficulty ?? "medium",
      deadline: input.deadline ?? null,
      codex_points_reward: input.codex_points_reward ?? 10
    }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-journal.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_journal_default = defineTool6({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List the signed-in user's journal entries, most recent first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional(),
    category: z5.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("journal_entries").select("id,title,content,category,mood,dominant_emotion,tags,importance,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/create-journal.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
var create_journal_default = defineTool7({
  name: "create_journal_entry",
  title: "Create journal entry",
  description: "Create a new journal entry for the signed-in user.",
  inputSchema: {
    title: z6.string().min(1),
    content: z6.string().optional(),
    category: z6.string().optional(),
    mood: z6.string().optional(),
    tags: z6.array(z6.string()).optional(),
    importance: z6.enum(["low", "normal", "high", "critical"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("journal_entries").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      content: input.content ?? "",
      category: input.category ?? "general",
      mood: input.mood ?? null,
      tags: input.tags ?? [],
      importance: input.importance ?? "normal"
    }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "wlygujlvsfimhtqsdxrx";
var mcp_default = defineMcp({
  name: "vantara-mcp",
  title: "VANTARA.EXE",
  version: "0.1.0",
  instructions: "Tools for the VANTARA / CODEXOS RPG life-ops platform. Read and create councils, personas, quests, and journal entries for the signed-in operator. Every call is scoped to that user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_councils_default,
    list_personas_default,
    list_quests_default,
    create_quest_default,
    list_journal_default,
    create_journal_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
