-- GAME_MASTER mode: streak insurance, consequence quests, dynamic difficulty

-- Streak insurance: allows users to protect one streak break per period
CREATE TABLE IF NOT EXISTS streak_insurance (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  task_id      uuid REFERENCES tasks(id) ON DELETE SET NULL,
  quest_id     uuid REFERENCES quests(id) ON DELETE SET NULL,
  used_at      timestamptz,
  expires_at   timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  status       text NOT NULL DEFAULT 'available' CHECK (status IN ('available','used','expired')),
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE streak_insurance ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Users manage own insurance" ON streak_insurance
    FOR ALL USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Consequence quest linking: failing a habit quest can trigger a consequence
ALTER TABLE quests
  ADD COLUMN IF NOT EXISTS consequence_quest_id uuid REFERENCES quests(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS difficulty_rating     float DEFAULT 5.0 CHECK (difficulty_rating BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS is_consequence        boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS parent_task_id        uuid REFERENCES tasks(id) ON DELETE SET NULL;

-- GAME_MASTER event log: narrative events generated by the game master
CREATE TABLE IF NOT EXISTS game_master_events (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type   text NOT NULL, -- streak_broken | streak_milestone | challenge_unlocked | consequence_triggered | level_up_narrative
  title        text NOT NULL,
  narrative    text,
  xp_delta     int  DEFAULT 0,
  quest_ids    uuid[],
  metadata     jsonb,
  created_at   timestamptz DEFAULT now()
);

ALTER TABLE game_master_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Users view own events" ON game_master_events
    FOR ALL USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Dynamic difficulty tracking per user
CREATE TABLE IF NOT EXISTS user_difficulty_profile (
  user_id        uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  current_level  float NOT NULL DEFAULT 5.0,
  avg_completion float NOT NULL DEFAULT 0.7,
  streak_avg     float NOT NULL DEFAULT 0.0,
  last_adjusted  timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

ALTER TABLE user_difficulty_profile ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Users manage own difficulty" ON user_difficulty_profile
    FOR ALL USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
