-- Semantic memory: pgvector embeddings on mavis_persona_memory.
-- Enables MAVIS to recall relevant context by meaning, not just keywords.
-- Embeddings generated by mavis-memory-embed function using gte-small (384-dim).

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE public.mavis_persona_memory
  ADD COLUMN IF NOT EXISTS embedding vector(384);

CREATE INDEX IF NOT EXISTS idx_persona_memory_embedding
  ON public.mavis_persona_memory
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- RPC: semantic nearest-neighbour search over persona memory
CREATE OR REPLACE FUNCTION public.match_persona_memory(
  query_embedding vector(384),
  match_user_id   uuid,
  match_threshold float  DEFAULT 0.25,
  match_count     int    DEFAULT 5
)
RETURNS TABLE (
  key        text,
  value      text,
  category   text,
  importance integer,
  similarity float
)
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT
    key,
    value,
    category,
    importance,
    1 - (embedding <=> query_embedding) AS similarity
  FROM public.mavis_persona_memory
  WHERE user_id = match_user_id
    AND embedding IS NOT NULL
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;
