-- Customer AI Agents — premium product tier above standard widgets
-- Separate from widget_instances; powered by Claude, not Gemini

create table if not exists customer_agents (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id) on delete cascade,

  -- Customer info
  customer_name   text not null,
  customer_email  text,
  business_name   text not null,
  business_type   text,                     -- e.g. "salon", "law firm", "ecommerce"

  -- Agent identity
  agent_name      text not null default 'AI Assistant',
  agent_persona   text not null,            -- full system prompt generated by MAVIS
  capabilities    text[] default '{}',      -- ['faq','lead_capture','booking','product_info','support']
  knowledge_base  text default '',          -- business context, FAQs, product info
  tone            text default 'friendly',  -- friendly | professional | casual | formal

  -- Brand
  brand_color     text default '#1a56db',
  brand_name      text,
  logo_url        text,

  -- Deployment
  plan_tier       text not null default 'widget', -- widget | hosted | custom
  embed_token     text unique default encode(gen_random_bytes(24), 'hex'),
  deploy_slug     text unique,              -- for hosted: agent.prymalai.com/[slug]
  status          text not null default 'active', -- active | paused | suspended

  -- Billing
  monthly_price_cents integer default 19700,

  -- Stats (updated by edge function)
  total_conversations integer default 0,
  total_messages      integer default 0,

  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create index on customer_agents(user_id);
create index on customer_agents(embed_token);
create index on customer_agents(deploy_slug);

alter table customer_agents enable row level security;
create policy "operators manage own customer agents"
  on customer_agents for all using (auth.uid() = user_id);

-- Message log for customer agent conversations
create table if not exists customer_agent_messages (
  id          uuid primary key default gen_random_uuid(),
  agent_id    uuid not null references customer_agents(id) on delete cascade,
  session_id  text not null,               -- client-generated session identifier
  role        text not null check (role in ('user','agent')),
  content     text not null,
  ts          timestamptz default now()
);

create index on customer_agent_messages(agent_id, session_id);
create index on customer_agent_messages(agent_id, ts desc);

alter table customer_agent_messages enable row level security;
-- Public insert (widget users), owner select
create policy "agent owner reads messages"
  on customer_agent_messages for select
  using (
    exists (
      select 1 from customer_agents ca
      where ca.id = customer_agent_messages.agent_id
        and ca.user_id = auth.uid()
    )
  );
create policy "public insert messages"
  on customer_agent_messages for insert
  with check (true);
