-- Fixes three tables referenced in edge function code but never migrated.
-- All three were causing silent INSERT failures at runtime.

-- ── 1. mavis_vault ────────────────────────────────────────────────────────────
-- Stores operator-approved system decisions (distinct from vault_entries, which
-- holds the operator's personal documents). Mirrors vault_entries schema so
-- handleSystemChange can write approved proposals here without a separate read path.
CREATE TABLE IF NOT EXISTS public.mavis_vault (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title      text NOT NULL,
  content    text NOT NULL DEFAULT '',
  category   text NOT NULL DEFAULT 'business',
  importance text NOT NULL DEFAULT 'medium',
  attachments text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.mavis_vault ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users own vault decisions"
  ON public.mavis_vault FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "service role manages mavis_vault"
  ON public.mavis_vault FOR ALL USING (auth.role() = 'service_role');
CREATE INDEX IF NOT EXISTS idx_mavis_vault_user_created
  ON public.mavis_vault(user_id, created_at DESC);

-- ── 2. mavis_activities ───────────────────────────────────────────────────────
-- Action audit log: every execution step, approval, session update, and outreach
-- attempt that task-executor processes writes a row here so nothing is lost.
-- Field names match what task-executor code inserts: type, description, xp_earned.
CREATE TABLE IF NOT EXISTS public.mavis_activities (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  task_id     uuid,
  type        text NOT NULL,   -- session_update_applied | action_executed | system_change_approved | outreach_sent | email_reply_sent
  description text,
  xp_earned   integer NOT NULL DEFAULT 0,
  payload     jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.mavis_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users own activities"
  ON public.mavis_activities FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "service role manages all activities"
  ON public.mavis_activities FOR ALL USING (auth.role() = 'service_role');
CREATE INDEX IF NOT EXISTS idx_mavis_activities_user_created
  ON public.mavis_activities(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mavis_activities_task
  ON public.mavis_activities(task_id) WHERE task_id IS NOT NULL;

-- ── 3. mavis_outreach_drafts ──────────────────────────────────────────────────
-- Reconnect message drafts generated by ambient-monitor for dormant contacts.
-- Field name is drafted_message to match ambient-monitor insert code.
CREATE TABLE IF NOT EXISTS public.mavis_outreach_drafts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id      uuid,
  contact_name    text,
  drafted_message text NOT NULL,
  status          text NOT NULL DEFAULT 'pending',  -- pending | approved | sent | rejected
  task_id         uuid,
  sent_at         timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.mavis_outreach_drafts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users own outreach drafts"
  ON public.mavis_outreach_drafts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "service role manages all outreach drafts"
  ON public.mavis_outreach_drafts FOR ALL USING (auth.role() = 'service_role');
CREATE INDEX IF NOT EXISTS idx_mavis_outreach_drafts_user_status
  ON public.mavis_outreach_drafts(user_id, status);

-- ── 4. Performance indexes (identified in audit) ──────────────────────────────
-- Missing index on mavis_revenue(user_id): task-executor queries it 3×.
CREATE INDEX IF NOT EXISTS idx_mavis_revenue_user
  ON public.mavis_revenue(user_id);

-- Missing index on profiles(user_id): ambient-monitor and task-executor query it.
CREATE INDEX IF NOT EXISTS idx_profiles_user_id
  ON public.profiles(user_id);

-- ── 5. RLS for prymal_clients ─────────────────────────────────────────────────
-- Audit found prymal_clients had no RLS — stores sensitive OAuth tokens and
-- owner contact info. Restricting to service_role only.
ALTER TABLE IF EXISTS public.prymal_clients ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'prymal_clients' AND policyname = 'service role manages prymal clients'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "service role manages prymal clients"
        ON public.prymal_clients FOR ALL USING (auth.role() = 'service_role')
    $policy$;
  END IF;
END
$$;
