// MAVIS Autonomy Orchestrator
// Unified control surface wrapping mavis-autonomous-engine / autonomous-runner / crew-orchestrator.
// GET  -> returns recent plans, steps, queued actions, and runs for the calling user
// POST -> creates a new plan from a goal, seeds initial steps, and kicks the engine

import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { createClient } from "npm:@supabase/supabase-js@2";
import { aiComplete } from "../_shared/providers.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY")!;

// Free-first provider cascade (shared): free Gemini → Groq → Lovable gateway → paid tiers.
async function planWithLLM(goal: string, context: string) {
  try {
    const { content } = await aiComplete({
      system:
        "You are MAVIS's autonomy planner. Given a goal, break it into 3-7 concrete, executable steps. " +
        "Return STRICT JSON: {\"title\":string,\"summary\":string,\"steps\":[{\"title\":string,\"description\":string,\"type\":\"research\"|\"action\"|\"decision\"|\"review\"}]}",
      user: `Goal: ${goal}\n\nContext: ${context || "(none)"}`,
    });
    const cleaned = content.replace(/```json|```/g, "").trim();
    return JSON.parse(cleaned);
  } catch (err) {
    console.warn("[orchestrator] planner failed:", err instanceof Error ? err.message : err);
    return {
      title: goal.slice(0, 80),
      summary: "Autogenerated fallback plan (LLM unavailable).",
      steps: [
        { title: "Investigate", description: goal, type: "research" },
        { title: "Draft approach", description: "Sketch the plan.", type: "decision" },
        { title: "Execute", description: "Do the work.", type: "action" },
        { title: "Review", description: "Verify results.", type: "review" },
      ],
    };
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization") ?? "";
    const jwt = authHeader.replace(/^Bearer\s+/i, "");
    if (!jwt) return new Response(JSON.stringify({ error: "Missing auth" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const supabaseUser = createClient(SUPABASE_URL, SERVICE_KEY, { global: { headers: { Authorization: `Bearer ${jwt}` } } });
    const { data: userData } = await supabaseUser.auth.getUser(jwt);
    const uid = userData?.user?.id;
    if (!uid) return new Response(JSON.stringify({ error: "Invalid user" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const admin = createClient(SUPABASE_URL, SERVICE_KEY);

    if (req.method === "GET") {
      const [plansRes, stepsRes, queueRes, runsRes] = await Promise.all([
        admin.from("mavis_plans").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(20),
        admin.from("mavis_plan_steps").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(200),
        admin.from("mavis_action_queue").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(50),
        admin.from("mavis_autonomous_runs").select("*").order("triggered_at", { ascending: false }).limit(20),
      ]);
      return new Response(
        JSON.stringify({
          plans: plansRes.data ?? [],
          steps: stepsRes.data ?? [],
          queue: queueRes.data ?? [],
          runs: runsRes.data ?? [],
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    if (req.method === "POST") {
      const body = await req.json().catch(() => ({}));
      const action = String(body.action || "plan");

      if (action === "run_cycle") {
        // Fire-and-forget the autonomous engine
        fetch(`${SUPABASE_URL}/functions/v1/mavis-autonomous-engine`, {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${SERVICE_KEY}` },
          body: JSON.stringify({ user_id: uid, trigger: "manual" }),
        }).catch((err) => console.warn("[orchestrator] engine kick failed:", err));

        await admin.from("mavis_autonomous_runs").insert({
          job_name: "manual-orchestrator-cycle",
          status: "triggered",
          notes: `Triggered by user ${uid}`,
        });
        return new Response(JSON.stringify({ ok: true, message: "Cycle triggered" }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }

      // Default: create plan from goal
      const goal = String(body.goal || "").trim();
      const context = String(body.context || "").trim();
      if (!goal) return new Response(JSON.stringify({ error: "goal required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });

      const plan = await planWithLLM(goal, context);
      const { data: planRow, error: planErr } = await admin
        .from("mavis_plans")
        .insert({
          user_id: uid,
          title: plan.title || goal.slice(0, 80),
          goal,
          summary: plan.summary || null,
          status: "active",
          total_steps: plan.steps?.length ?? 0,
          done_steps: 0,
          context: { source: "autonomy-orchestrator", raw_context: context },
        })
        .select()
        .single();

      if (planErr) throw planErr;

      const stepsToInsert = (plan.steps ?? []).map((s: any, idx: number) => ({
        plan_id: planRow.id,
        user_id: uid,
        step_index: idx,
        step_order: idx,
        title: s.title || `Step ${idx + 1}`,
        description: s.description || null,
        type: s.type || "action",
        status: "pending",
      }));

      if (stepsToInsert.length) {
        const { error: stepsErr } = await admin.from("mavis_plan_steps").insert(stepsToInsert);
        if (stepsErr) console.warn("[orchestrator] steps insert:", stepsErr.message);
      }

      return new Response(JSON.stringify({ ok: true, plan: planRow, steps: stepsToInsert.length }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (err) {
    console.error("[orchestrator] error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "unknown" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
